service: astroport-graph-api

variablesResolutionMode: 20210326

plugins:
  - serverless-offline
#  - serverless-dotenv-plugin
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    DECIMALS: ${self:custom.environment.DECIMALS}
    START_BLOCK_HEIGHT: ${self:custom.environment.START_BLOCK_HEIGHT}
    TERRA_LCD: ${self:custom.environment.TERRA_LCD}
    TERRA_MANTLE: ${self:custom.environment.TERRA_MANTLE}
    TERRA_CHAIN_ID: ${self:custom.environment.TERRA_CHAIN_ID}
    MONGODB_URL: ${self:custom.environment.MONGODB_URL}

functions:
  collector:
    handler: src/collector/index.run
    events:
      - schedule: rate(3 minutes)
  graphql:
    handler: src/graphql/index.run
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

custom:
  environment: ${file(env.yml):${opt:stage, "dev"}, file(env.yml):default}
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.serverless.json"
  serverless-offline:
    httpPort: 4000
