service: astroport-graph-api
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-offline
#  - serverless-dotenv-plugin
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    DECIMALS: ${env:DECIMALS}
    START_BLOCK_HEIGHT: ${env:START_BLOCK_HEIGHT}
    TERRA_LCD: ${env:TERRA_LCD}
    TERRA_MANTLE: ${env:TERRA_MANTLE}
    TERRA_CHAIN_ID: ${env:TERRA_CHAIN_ID}
    MONGODB_URL: ${env:MONGODB_URL}

functions:
  aggregator:
    handler: src/aggregator/index.run
    events:
      - schedule: rate(2 minutes)
    timeout: 115 # in seconds
  collector:
    handler: src/collector/index.run
    events:
      - schedule: rate(3 minutes)
  graphql:
    handler: src/graphql/index.run
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

custom:
  environment: ${file(.env)}
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.serverless.json"
  serverless-offline:
    httpPort: 4000
